# Generated by Django 5.0.2 on 2024-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_description', models.TextField()),
                ('Product_image', models.ImageField(upload_to='Product_images/')),
                ('Product_stars', models.IntegerField()),
                ('Product_available_quantity', models.IntegerField()),
                ('Product_single_price', models.FloatField()),
            ],
        ),
    ]
