# Generated by Django 5.0.6 on 2024-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
