# Generated by Django 5.0.6 on 2024-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(null=True, upload_to='Product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_url',
            field=models.URLField(null=True),
        ),
    ]
