# Generated by Django 5.0.6 on 2024-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_old_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_description',
            field=models.TextField(default='Unknown description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(default=None, null=True, upload_to='Product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(default='Unknown product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_single_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_stars',
            field=models.IntegerField(default=0),
        ),
    ]
