# Generated by Django 5.0.6 on 2024-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_old_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
