# Generated by Django 5.0.6 on 2024-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='app\\static\\app\\Product_images\\'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
